micronaut:
  application:
    name: authorization
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
  security:
    intercept-url-map:
    - access: isAnonymous()
      pattern: /swagger/**
    - access: isAnonymous()
      pattern: /swagger-ui/**
    -
      pattern: /intercept/allowed-to-authenticated
      access: isAuthenticated()
    -
      pattern: /intercept/allowed-to-everyone
      access: isAnonymous()
    -
      pattern: /intercept/allowed-to-admin
      access:
        - ROLE_ADMIN
    oauth2:
      clients:
        google:
          client-id: ${GOOGLE_CLIENT_ID}
          client-secret: ${GOOGLE_CLIENT_SECRET}
          openid:
            issuer: https://accounts.google.com
        yandex:
          client-id: ${YANDEX_CLIENT_ID}
          client-secret: ${YANDEX_CLIENT_SECRET}
          authorization:
            url: https://oauth.yandex.ru/authorize
          token:
            url: https://oauth.yandex.ru/token
            auth-method: client_secret_post
#          scopes:
#            - "login:email"
#            - "login:info"
#            - "login:avatar"
        vk:
          client-id: ${VK_CLIENT_ID}
          client-secret: ${VK_CLIENT_SECRET}
          authorization:
            url: https://oauth.vk.com/authorize
          token:
            url: https://oauth.vk.com/access_token
            auth-method: client_secret_post
    authentication: cookie
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: ${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}
netty:
  default:
    allocator:
      max-order: 3
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/authorization_example
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    db-type: postgres
    dialect: POSTGRES
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
jpa.default.properties.hibernate.hbm2ddl.auto: update
flyway:
  datasources:
    default:
      enabled: false